export const germanTypes = {
  fire: { name: "Feuer", svg: "./images/type-icons/fire.svg" },
  grass: { name: "Pflanze", svg: "./images/type-icons/grass.svg" },
  water: { name: "Wasser", svg: "./images/type-icons/water.svg" },
  bug: { name: "Käfer", svg: "./images/type-icons/bug.svg" },
  normal: { name: "Normal", svg: "./images/type-icons/normal.svg" },
  poison: { name: "Gift", svg: "./images/type-icons/poison.svg" },
  electric: { name: "Elektro", svg: "./images/type-icons/electric.svg" },
  ground: { name: "Boden", svg: "./images/type-icons/ground.svg" },
  fairy: { name: "Fee", svg: "./images/type-icons/fairy.svg" },
  psychic: { name: "Psycho", svg: "./images/type-icons/psychic.svg" },
  fighting: { name: "Kampf", svg: "./images/type-icons/fighting.svg" },
  rock: { name: "Gestein", svg: "./images/type-icons/rock.svg" },
  ice: { name: "Eis", svg: "./images/type-icons/ice.svg" },
  dragon: { name: "Drache", svg: "./images/type-icons/dragon.svg" },
  dark: { name: "Unlicht", svg: "./images/type-icons/dark.svg" },
  ghost: { name: "Geist", svg: "./images/type-icons/ghost.svg" },
  steel: { name: "Stahl", svg: "./images/type-icons/steel.svg" },
  flying: { name: "Flug", svg: "./images/type-icons/flying.svg" },
};
